name: Python Complete CI/CD Pipeline

# 触发条件：推送到主要分支、创建PR或手动触发
on:
  push:
    branches: [ main, int ]  # 主分支和开发分支
    paths-ignore:  # 忽略 Markdown/配置文件变更，避免无效触发
      - '**.md'          # 忽略所有 Markdown 文件
      - '.gitignore'     # 忽略 .gitignore 文件
  pull_request:
    branches: [ main, int ]
    paths-ignore:  # 忽略 Markdown/配置文件变更，避免无效触发
      - '**.md'          # 忽略所有 Markdown 文件
      - '.gitignore'     # 忽略 .gitignore 文件
  workflow_dispatch:  # 允许手动触发
      
# 环境变量配置
env:
  # 基础配置
  PROJECT_NAME: "learngit"
  JAVA_VERSION: "11"
  MAVEN_VERSION: "3.9.5"
  # Docker 镜像配置
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "ghcr.io/dqpylf/learngit"
  # 目录配置
  SRC_DIR: "src/main/python"

# 工作流任务
jobs:
  ###########################
  # 1. 准备阶段：代码检出和环境设置
  ###########################
  prepare:
    runs-on: ubuntu-latest
    outputs:
      # 输出Java版本用于后续任务
      java-version: ${{ env.JAVA_VERSION }}
      # 输出当前提交哈希用于版本标识
      commit-hash: ${{ github.sha }}
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史用于版本号生成

      - name: 设置Java环境
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: 缓存Maven依赖
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 验证Maven配置
        run: |
          mvn --version
          java -version

  ###########################
  # 2. 代码质量检查 - 暂时注释掉
  ###########################
  # code-quality:
  #   needs: prepare
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 检出代码
  #       uses: actions/checkout@v4
  #
  #     - name: 恢复Python环境
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ needs.prepare.outputs.python-version }}
  #
  #     - name: 恢复依赖缓存
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ hashFiles(env.REQUIREMENTS_FILE, env.DEV_REQUIREMENTS_FILE) }}
  #
  #     - name: 安装依赖
  #       run: |
  #         pip install -r ${{ env.DEV_REQUIREMENTS_FILE }}
  #
  #     - name: 代码风格检查 (flake8)
  #       run: |
  #         flake8 ${{ env.SRC_DIR }} \
  #           --count \
  #           --exit-zero \
  #           --max-complexity=10 \
  #           --max-line-length=127 \
  #           --statistics
  #         # flake8 ${{ env.SRC_DIR }} ${{ env.TEST_DIR }} \  # 暂时注释掉测试目录检查
  #
  #     - name: 代码格式化检查 (black)
  #       run: |
  #         black --check ${{ env.SRC_DIR }}
  #         # black --check ${{ env.SRC_DIR }} ${{ env.TEST_DIR }}  # 暂时注释掉测试目录检查
  #
  #     - name: 导入顺序检查 (isort)
  #       run: |
  #         isort --check --profile black ${{ env.SRC_DIR }}
  #         # isort --check --profile black ${{ env.SRC_DIR }} ${{ env.TEST_DIR }}  # 暂时注释掉测试目录检查
  #
  #     - name: 静态类型检查 (mypy)
  #       run: |
  #         mypy ${{ env.SRC_DIR }} --ignore-missing-imports
  #
  #     - name: 代码质量评分 (pylint)
  #       run: |
  #         pylint ${{ env.SRC_DIR }} --fail-under=${{ env.LINT_THRESHOLD }}

  ###########################
  # 3. 测试阶段 - 暂时注释掉
  ###########################
  # test:
  #   needs: code-quality
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # 测试多个Python版本确保兼容性
  #       python-version: ["3.9", "3.10", "3.11"]
  #       # 测试不同环境配置
  #       environment: ["development", "production"]
  #     fail-fast: false  # 一个版本失败不影响其他版本测试
  #
  #   steps:
  #     - name: 检出代码
  #       uses: actions/checkout@v4
  #
  #     - name: 设置Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #
  #     - name: 恢复依赖缓存
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles(env.REQUIREMENTS_FILE) }}
  #
  #     - name: 安装依赖
  #       run: |
  #         pip install -r ${{ env.REQUIREMENTS_FILE }}
  #         pip install -r ${{ env.DEV_REQUIREMENTS_FILE }}
  #
  #     - name: 准备测试报告目录
  #       run: mkdir -p ${{ env.TEST_REPORT_DIR }}
  #
  #     - name: 运行测试 (pytest)
  #       env:
  #         APP_ENV: ${{ matrix.environment }}
  #         TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
  #       run: |
  #         pytest ${{ env.TEST_DIR }} \
  #           --cov=${{ env.SRC_DIR }} \
  #           --cov-report=xml \
  #           --cov-report=term \
  #           --junitxml=${{ env.TEST_REPORT_DIR }}/results-${{ matrix.python-version }}-${{ matrix.environment }}.xml \
  #           -v
  #
  #     - name: 上传测试报告
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: test-reports-${{ matrix.python-version }}-${{ matrix.environment }}
  #         path: ${{ env.TEST_REPORT_DIR }}
  #
  #     - name: 上传覆盖率报告到Codecov
  #       uses: codecov/codecov-action@v3
  #       with:
  #         file: ./coverage.xml
  #         flags: unittests
  #         name: codecov-${{ matrix.python-version }}
  #         fail_ci_if_error: true

  ###########################
  # 4. Docker镜像构建阶段
  ###########################
  build:
    needs: prepare  # 直接从准备阶段开始构建（暂时跳过代码质量检查和测试）
    runs-on: ubuntu-latest
    # 只在特定分支构建
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/int'
    outputs:
      version: ${{ steps.version-generator.outputs.version }}
      image-tag: ${{ steps.version-generator.outputs.image-tag }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 需要完整历史来生成版本号

      - name: 设置Java环境
        uses: actions/setup-java@v4
        with:
          java-version: ${{ needs.prepare.outputs.java-version }}
          distribution: 'temurin'

      - name: 恢复Maven依赖缓存
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: 生成版本号和镜像标签
        id: version-generator
        run: |
          # 检查是否存在tag
          if git describe --abbrev=0 --tags 2>/dev/null; then
            # 存在tag，使用最近的tag
            LAST_TAG=$(git describe --abbrev=0 --tags)
            HAS_TAG=true
          else
            # 不存在tag，使用默认版本
            LAST_TAG="v0.0.0"
            HAS_TAG=false
          fi
          
          echo "最近的tag: $LAST_TAG (存在真实tag: $HAS_TAG)"
          
          # 提取主版本号
          MAJOR=$(echo $LAST_TAG | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $LAST_TAG | cut -d. -f2)
          PATCH=$(echo $LAST_TAG | cut -d. -f3)
          
          # 根据分支生成不同的标签
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # 主分支使用语义版本号
            NEW_PATCH=$((PATCH + 1))
            VERSION="v$MAJOR.$MINOR.$NEW_PATCH"
            IMAGE_TAG="$MAJOR.$MINOR.$NEW_PATCH"
          else
            # 开发分支使用开发版本号
            if [[ "$HAS_TAG" == "true" ]]; then
              COMMIT_COUNT=$(git rev-list --count HEAD ^$LAST_TAG)
            else
              COMMIT_COUNT=$(git rev-list --count HEAD)
            fi
            SHORT_SHA=$(echo "${{ needs.prepare.outputs.commit-hash }}" | cut -c1-8)
            VERSION="$LAST_TAG-dev.$COMMIT_COUNT+$SHORT_SHA"
            IMAGE_TAG="dev-$SHORT_SHA"
          fi
          
          echo "生成版本号: $VERSION"
          echo "生成镜像标签: $IMAGE_TAG"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送Docker镜像 (使用 Jib)
        run: |
          mvn clean compile jib:build \
            -Djib.to.image=${{ env.IMAGE_NAME }}:${{ steps.version-generator.outputs.image-tag }}
            
      - name: 推送latest标签 (仅main分支)
        if: github.ref == 'refs/heads/main'
        run: |
          mvn jib:build \
            -Djib.to.image=${{ env.IMAGE_NAME }}:latest

  ###########################
  # 5. 部署阶段 - 开发环境
  ###########################
  deploy-dev:
    needs: [build, prepare]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/int'  # 只在开发分支部署到开发环境
    environment:
      name: development
      url: https://${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}
    steps:
      - name: 镜像部署成功通知
        run: |
          echo "Docker镜像已成功推送到开发环境"
          echo "镜像地址: ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image-tag }}"
          echo "镜像版本: ${{ needs.build.outputs.version }}"
          

  ###########################
  # 6. 部署阶段 - 生产环境
  ###########################
  deploy-prod:
    needs: [build, prepare]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # 只在主分支部署到生产环境
    environment:
      name: production  # 需在GitHub仓库设置中配置保护规则，如手动批准
      url: https://${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.PROJECT_NAME }}
    steps:
      - name: 验证生产镜像版本
        run: |
          # 验证版本号格式（语义版本）
          VERSION="${{ needs.build.outputs.version }}"
          if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "错误: 生产版本号格式不正确: $VERSION"
            echo "期望格式: v1.2.3"
            exit 1
          fi
          echo "版本号验证通过: $VERSION"

      - name: 镜像生产环境部署成功通知
        run: |
          echo "Docker镜像已成功推送到生产环境"
          echo "镜像地址: ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image-tag }}"
          echo "镜像版本: ${{ needs.build.outputs.version }}"
          echo "Latest标签: ${{ env.IMAGE_NAME }}:latest"

      - name: 创建GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.version }}
          name: Release ${{ needs.build.outputs.version }}
          body: |
            **新版本发布**: ${{ needs.build.outputs.version }}
            
            ## Docker 镜像
            
            ```bash
            # 拉取镜像
            docker pull ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image-tag }}
            docker pull ${{ env.IMAGE_NAME }}:latest
            
            # 运行容器
            docker run -p 5001:5001 ${{ env.IMAGE_NAME }}:latest
            ```
            
            ## 变更内容
            
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
